"use client";

import { useState, useEffect, use } from 'react';
import EstimatedPreview from '../../components/EstimatedPreview';
import QuotationPreview from '../../components/QuotationPreview';

export default function PublicSharePage({ params }) {
  // Use React.use() to unwrap params in Next.js 15+ if needed, or just await in useEffect.
  // params is a Promise in recent Next.js versions for Server Components, but this is a Client Component.
  // In Client Components, params is passed as a prop, but dealing with async params is safer.
  const resolvedParams = use(params);
  const publicId = resolvedParams.publicId;

  const [docData, setDocData] = useState(null);
  const [docType, setDocType] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const res = await fetch(`/api/public/document/${publicId}`);
        if (!res.ok) {
            if (res.status === 404) throw new Error('Document not found');
            throw new Error('Failed to load document');
        }
        
        const responseData = await res.json();
        setDocData(responseData.data);
        setDocType(responseData.type);
        
        // set title
        const client = responseData.data?.receiver?.name || responseData.data?.receiver?.company || responseData.data?.clientName || 'Client';
        document.title = `${responseData.type} - ${client}`;

      } catch (err) {
        console.error(err);
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    if (publicId) fetchData();
  }, [publicId]);

  if (loading) return (
      <div className="flex items-center justify-center min-h-screen bg-slate-50">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
  );

  if (error) return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-slate-50 gap-4">
          <div className="text-red-500 text-xl font-bold">😕 Oops!</div>
          <div className="text-slate-600">{error}</div>
      </div>
  );

  if (!docData) return null;

  return (
    <div className="min-h-screen bg-slate-100 flex flex-col items-center py-8">
       {/* Public Header */}
       <div className="mb-6 no-print w-full max-w-[210mm] flex justify-between items-center px-4 md:px-0">
          <div className="text-sm text-slate-500">
              Shared {docType}
          </div>
          <button 
            onClick={() => window.print()} 
            className="bg-blue-600 text-white px-4 py-2 rounded-lg shadow hover:bg-blue-700 transition flex items-center gap-2 font-medium"
          >
            <span>🖨️</span> Print / Save PDF
          </button>
       </div>

       <div className="shadow-2xl bg-white">
          {docType === 'Estimate' ? (
              <EstimatedPreview data={docData} showGst={docData.showGst} />
          ) : (
              <QuotationPreview data={docData} />
          )}
       </div>

       <div className="mt-8 text-slate-400 text-xs text-center no-print">
           Generated by Champion Security Services
       </div>

       <style jsx global>{`
          @media print {
            .no-print { display: none !important; }
            body { background: white; }
          }
       `}</style>
    </div>
  );
}
